spring.application.name=ClinicQ


 

General.EXCEPTION_MESSAGE=Some Error occurred


 

#Service


 

Service.NO_DOCTORS_FOUND=No Doctors found in this department

Service.NO_DOCTOR_FOUND=No doctor found with the given Id


 

Service.NO_TIMESLOTS_FOUND=No timeSlots found

Service.NO_TIMESLOT_FOUND=No timeSlot found


 

Service.NO_PATIENT_FOUND=No patient details found


 

Service.USER_EXISTS=User already exists


 

Service.INVALID_USER=User not found

Service.INVALID_CREDENTIALS=Invalid credentials


 

Service.SLOT_DOES_NOT_BELONG_TO_DOCTOR=The time Slot Does not Belong to the doctor


 

Service.ALREADY_BOOKED=The slot is already booked please select a diffrent slot

Service.NO_ADMIN_FOUND=Admin config not found


 

Service.APPOINTMENT_NOT_FOUND=Appointment not found

Service.NO_UPCOMING_APPOINTMENT_FOUND=No upcoming appointments found


 

Service.INVALID_TIME_RANGE=Invalid date range


 

Service.NO_TOKEN_FOUND="No token found"

Service.TOKEN_EXPIRED=Token expired


 

Service.NO_HISTORY_FOUND=No past Appointments found

Service.CANNOT_BOOK_PAST_APPOINTMENT=Past Appointment can not be booked


 

Service.ALREADY_CANCELLED=The appointment has already been cancellled

Service.CANCELLATION_NOT_ALLOWED=Cancellation not allowed beyond cutofF Hours


 

Service.RESCHEDULE_NOT_ALLOWED=cannot reschedule after current time

Service.USER_DETAILS_REQUIRED=User details are required

Service.USER_NOT_FOUND=User not found

Service.USER_ALREADY_PRESENT=The User with email Id Already exists


 

Service.NO_QUEUE_FOUND=No queue for this doctor today


 

Service.ACCOUNT_LOCKED=Account locked. Try later.


 

Service.UNAUTHORIZED_ACCESS=User not authorized to access this page


 

#API

Api.NO_DEPT_FOUND=No Department found

Api.BOOKING_SUCCESS=Appointment Booked Successfully with id:


 

# Fix these lines to match the Java code exactly

API.ADD_DOCTOR_SUCCESS=Doctor added successfully with id:

API.CONFIGURE_SUCCESS=Doctor Schedule configured successfully for id:

API.DELETE_SUCCESS=Doctor deleted successfully


 

Api.CANCELING_SUCCESS=Cancelled

API.GENERATE_SUCCESS=Time slots generated successfully

API.UPDATE_SUCCESS=Booking rules updated successfully

API.TOKEN_UPDATE_SUCCESS=Token status updated successfully

API.SIGNUP_SUCCESS=Signed up successfully

API.REG_SUCCESS=Patient Registered Successfully

API.RESET_SUCCESS=Password updated successfully




 

#MySQL settings

#Change these settings according to database you are using

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db

spring.datasource.username=root

#If MySQL installation is password proctored,then use below property to set password

spring.datasource.password=1234


 

#spring security

spring.security.user.name=admin

spring.security.user.password=123


 

#JPA settings

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true



